/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SelectPlanRouteImport } from './routes/select-plan'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as VerifyTokenRouteImport } from './routes/verify.$token'
import { Route as ResetPasswordTokenRouteImport } from './routes/reset-password.$token'
import { Route as MenuSlugRouteImport } from './routes/menu.$slug'
import { Route as DashboardUsersRouteImport } from './routes/dashboard.users'
import { Route as DashboardSetupRouteImport } from './routes/dashboard.setup'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardQrRouteImport } from './routes/dashboard.qr'
import { Route as DashboardProjectsRouteImport } from './routes/dashboard.projects'
import { Route as DashboardOrdersRouteImport } from './routes/dashboard.orders'
import { Route as DashboardMenuRouteImport } from './routes/dashboard.menu'
import { Route as DashboardContentRouteImport } from './routes/dashboard.content'
import { Route as DashboardBillingRouteImport } from './routes/dashboard.billing'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard.analytics'
import { Route as AdminPlansRouteImport } from './routes/admin.plans'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminCafesRouteImport } from './routes/admin.cafes'
import { Route as AdminCafesIndexRouteImport } from './routes/admin.cafes.index'
import { Route as DashboardOrdersHistoryRouteImport } from './routes/dashboard.orders.history'
import { Route as AdminCafesIdRouteImport } from './routes/admin.cafes.$id'
import { Route as MenuSlugOrderTokenRouteImport } from './routes/menu.$slug.order.$token'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectPlanRoute = SelectPlanRouteImport.update({
  id: '/select-plan',
  path: '/select-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyTokenRoute = VerifyTokenRouteImport.update({
  id: '/verify/$token',
  path: '/verify/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordTokenRoute = ResetPasswordTokenRouteImport.update({
  id: '/reset-password/$token',
  path: '/reset-password/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuSlugRoute = MenuSlugRouteImport.update({
  id: '/menu/$slug',
  path: '/menu/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardUsersRoute = DashboardUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSetupRoute = DashboardSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardQrRoute = DashboardQrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProjectsRoute = DashboardProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOrdersRoute = DashboardOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMenuRoute = DashboardMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardContentRoute = DashboardContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBillingRoute = DashboardBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminPlansRoute = AdminPlansRouteImport.update({
  id: '/admin/plans',
  path: '/admin/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCafesRoute = AdminCafesRouteImport.update({
  id: '/admin/cafes',
  path: '/admin/cafes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCafesIndexRoute = AdminCafesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminCafesRoute,
} as any)
const DashboardOrdersHistoryRoute = DashboardOrdersHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => DashboardOrdersRoute,
} as any)
const AdminCafesIdRoute = AdminCafesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminCafesRoute,
} as any)
const MenuSlugOrderTokenRoute = MenuSlugOrderTokenRouteImport.update({
  id: '/order/$token',
  path: '/order/$token',
  getParentRoute: () => MenuSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/register': typeof RegisterRoute
  '/select-plan': typeof SelectPlanRoute
  '/settings': typeof SettingsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/cafes': typeof AdminCafesRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/plans': typeof AdminPlansRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/content': typeof DashboardContentRoute
  '/dashboard/menu': typeof DashboardMenuRoute
  '/dashboard/orders': typeof DashboardOrdersRouteWithChildren
  '/dashboard/projects': typeof DashboardProjectsRoute
  '/dashboard/qr': typeof DashboardQrRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/setup': typeof DashboardSetupRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/menu/$slug': typeof MenuSlugRouteWithChildren
  '/reset-password/$token': typeof ResetPasswordTokenRoute
  '/verify/$token': typeof VerifyTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/admin/cafes/$id': typeof AdminCafesIdRoute
  '/dashboard/orders/history': typeof DashboardOrdersHistoryRoute
  '/admin/cafes/': typeof AdminCafesIndexRoute
  '/menu/$slug/order/$token': typeof MenuSlugOrderTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/register': typeof RegisterRoute
  '/select-plan': typeof SelectPlanRoute
  '/settings': typeof SettingsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/plans': typeof AdminPlansRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/content': typeof DashboardContentRoute
  '/dashboard/menu': typeof DashboardMenuRoute
  '/dashboard/orders': typeof DashboardOrdersRouteWithChildren
  '/dashboard/projects': typeof DashboardProjectsRoute
  '/dashboard/qr': typeof DashboardQrRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/setup': typeof DashboardSetupRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/menu/$slug': typeof MenuSlugRouteWithChildren
  '/reset-password/$token': typeof ResetPasswordTokenRoute
  '/verify/$token': typeof VerifyTokenRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/admin/cafes/$id': typeof AdminCafesIdRoute
  '/dashboard/orders/history': typeof DashboardOrdersHistoryRoute
  '/admin/cafes': typeof AdminCafesIndexRoute
  '/menu/$slug/order/$token': typeof MenuSlugOrderTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/register': typeof RegisterRoute
  '/select-plan': typeof SelectPlanRoute
  '/settings': typeof SettingsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/cafes': typeof AdminCafesRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/plans': typeof AdminPlansRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/content': typeof DashboardContentRoute
  '/dashboard/menu': typeof DashboardMenuRoute
  '/dashboard/orders': typeof DashboardOrdersRouteWithChildren
  '/dashboard/projects': typeof DashboardProjectsRoute
  '/dashboard/qr': typeof DashboardQrRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/setup': typeof DashboardSetupRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/menu/$slug': typeof MenuSlugRouteWithChildren
  '/reset-password/$token': typeof ResetPasswordTokenRoute
  '/verify/$token': typeof VerifyTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/admin/cafes/$id': typeof AdminCafesIdRoute
  '/dashboard/orders/history': typeof DashboardOrdersHistoryRoute
  '/admin/cafes/': typeof AdminCafesIndexRoute
  '/menu/$slug/order/$token': typeof MenuSlugOrderTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/maintenance'
    | '/register'
    | '/select-plan'
    | '/settings'
    | '/verify-email'
    | '/admin/cafes'
    | '/admin/login'
    | '/admin/plans'
    | '/dashboard/analytics'
    | '/dashboard/billing'
    | '/dashboard/content'
    | '/dashboard/menu'
    | '/dashboard/orders'
    | '/dashboard/projects'
    | '/dashboard/qr'
    | '/dashboard/settings'
    | '/dashboard/setup'
    | '/dashboard/users'
    | '/menu/$slug'
    | '/reset-password/$token'
    | '/verify/$token'
    | '/admin/'
    | '/dashboard/'
    | '/admin/cafes/$id'
    | '/dashboard/orders/history'
    | '/admin/cafes/'
    | '/menu/$slug/order/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/maintenance'
    | '/register'
    | '/select-plan'
    | '/settings'
    | '/verify-email'
    | '/admin/login'
    | '/admin/plans'
    | '/dashboard/analytics'
    | '/dashboard/billing'
    | '/dashboard/content'
    | '/dashboard/menu'
    | '/dashboard/orders'
    | '/dashboard/projects'
    | '/dashboard/qr'
    | '/dashboard/settings'
    | '/dashboard/setup'
    | '/dashboard/users'
    | '/menu/$slug'
    | '/reset-password/$token'
    | '/verify/$token'
    | '/admin'
    | '/dashboard'
    | '/admin/cafes/$id'
    | '/dashboard/orders/history'
    | '/admin/cafes'
    | '/menu/$slug/order/$token'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/maintenance'
    | '/register'
    | '/select-plan'
    | '/settings'
    | '/verify-email'
    | '/admin/cafes'
    | '/admin/login'
    | '/admin/plans'
    | '/dashboard/analytics'
    | '/dashboard/billing'
    | '/dashboard/content'
    | '/dashboard/menu'
    | '/dashboard/orders'
    | '/dashboard/projects'
    | '/dashboard/qr'
    | '/dashboard/settings'
    | '/dashboard/setup'
    | '/dashboard/users'
    | '/menu/$slug'
    | '/reset-password/$token'
    | '/verify/$token'
    | '/admin/'
    | '/dashboard/'
    | '/admin/cafes/$id'
    | '/dashboard/orders/history'
    | '/admin/cafes/'
    | '/menu/$slug/order/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  MaintenanceRoute: typeof MaintenanceRoute
  RegisterRoute: typeof RegisterRoute
  SelectPlanRoute: typeof SelectPlanRoute
  SettingsRoute: typeof SettingsRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  AdminCafesRoute: typeof AdminCafesRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AdminPlansRoute: typeof AdminPlansRoute
  MenuSlugRoute: typeof MenuSlugRouteWithChildren
  ResetPasswordTokenRoute: typeof ResetPasswordTokenRoute
  VerifyTokenRoute: typeof VerifyTokenRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select-plan': {
      id: '/select-plan'
      path: '/select-plan'
      fullPath: '/select-plan'
      preLoaderRoute: typeof SelectPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$token': {
      id: '/verify/$token'
      path: '/verify/$token'
      fullPath: '/verify/$token'
      preLoaderRoute: typeof VerifyTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password/$token': {
      id: '/reset-password/$token'
      path: '/reset-password/$token'
      fullPath: '/reset-password/$token'
      preLoaderRoute: typeof ResetPasswordTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu/$slug': {
      id: '/menu/$slug'
      path: '/menu/$slug'
      fullPath: '/menu/$slug'
      preLoaderRoute: typeof MenuSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/users': {
      id: '/dashboard/users'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof DashboardUsersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/setup': {
      id: '/dashboard/setup'
      path: '/setup'
      fullPath: '/dashboard/setup'
      preLoaderRoute: typeof DashboardSetupRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/qr': {
      id: '/dashboard/qr'
      path: '/qr'
      fullPath: '/dashboard/qr'
      preLoaderRoute: typeof DashboardQrRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/projects': {
      id: '/dashboard/projects'
      path: '/projects'
      fullPath: '/dashboard/projects'
      preLoaderRoute: typeof DashboardProjectsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/orders': {
      id: '/dashboard/orders'
      path: '/orders'
      fullPath: '/dashboard/orders'
      preLoaderRoute: typeof DashboardOrdersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/menu': {
      id: '/dashboard/menu'
      path: '/menu'
      fullPath: '/dashboard/menu'
      preLoaderRoute: typeof DashboardMenuRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/content': {
      id: '/dashboard/content'
      path: '/content'
      fullPath: '/dashboard/content'
      preLoaderRoute: typeof DashboardContentRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/billing': {
      id: '/dashboard/billing'
      path: '/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof DashboardBillingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/plans': {
      id: '/admin/plans'
      path: '/admin/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof AdminPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cafes': {
      id: '/admin/cafes'
      path: '/admin/cafes'
      fullPath: '/admin/cafes'
      preLoaderRoute: typeof AdminCafesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cafes/': {
      id: '/admin/cafes/'
      path: '/'
      fullPath: '/admin/cafes/'
      preLoaderRoute: typeof AdminCafesIndexRouteImport
      parentRoute: typeof AdminCafesRoute
    }
    '/dashboard/orders/history': {
      id: '/dashboard/orders/history'
      path: '/history'
      fullPath: '/dashboard/orders/history'
      preLoaderRoute: typeof DashboardOrdersHistoryRouteImport
      parentRoute: typeof DashboardOrdersRoute
    }
    '/admin/cafes/$id': {
      id: '/admin/cafes/$id'
      path: '/$id'
      fullPath: '/admin/cafes/$id'
      preLoaderRoute: typeof AdminCafesIdRouteImport
      parentRoute: typeof AdminCafesRoute
    }
    '/menu/$slug/order/$token': {
      id: '/menu/$slug/order/$token'
      path: '/order/$token'
      fullPath: '/menu/$slug/order/$token'
      preLoaderRoute: typeof MenuSlugOrderTokenRouteImport
      parentRoute: typeof MenuSlugRoute
    }
  }
}

interface DashboardOrdersRouteChildren {
  DashboardOrdersHistoryRoute: typeof DashboardOrdersHistoryRoute
}

const DashboardOrdersRouteChildren: DashboardOrdersRouteChildren = {
  DashboardOrdersHistoryRoute: DashboardOrdersHistoryRoute,
}

const DashboardOrdersRouteWithChildren = DashboardOrdersRoute._addFileChildren(
  DashboardOrdersRouteChildren,
)

interface DashboardRouteChildren {
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardBillingRoute: typeof DashboardBillingRoute
  DashboardContentRoute: typeof DashboardContentRoute
  DashboardMenuRoute: typeof DashboardMenuRoute
  DashboardOrdersRoute: typeof DashboardOrdersRouteWithChildren
  DashboardProjectsRoute: typeof DashboardProjectsRoute
  DashboardQrRoute: typeof DashboardQrRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardSetupRoute: typeof DashboardSetupRoute
  DashboardUsersRoute: typeof DashboardUsersRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardBillingRoute: DashboardBillingRoute,
  DashboardContentRoute: DashboardContentRoute,
  DashboardMenuRoute: DashboardMenuRoute,
  DashboardOrdersRoute: DashboardOrdersRouteWithChildren,
  DashboardProjectsRoute: DashboardProjectsRoute,
  DashboardQrRoute: DashboardQrRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardSetupRoute: DashboardSetupRoute,
  DashboardUsersRoute: DashboardUsersRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface AdminCafesRouteChildren {
  AdminCafesIdRoute: typeof AdminCafesIdRoute
  AdminCafesIndexRoute: typeof AdminCafesIndexRoute
}

const AdminCafesRouteChildren: AdminCafesRouteChildren = {
  AdminCafesIdRoute: AdminCafesIdRoute,
  AdminCafesIndexRoute: AdminCafesIndexRoute,
}

const AdminCafesRouteWithChildren = AdminCafesRoute._addFileChildren(
  AdminCafesRouteChildren,
)

interface MenuSlugRouteChildren {
  MenuSlugOrderTokenRoute: typeof MenuSlugOrderTokenRoute
}

const MenuSlugRouteChildren: MenuSlugRouteChildren = {
  MenuSlugOrderTokenRoute: MenuSlugOrderTokenRoute,
}

const MenuSlugRouteWithChildren = MenuSlugRoute._addFileChildren(
  MenuSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  MaintenanceRoute: MaintenanceRoute,
  RegisterRoute: RegisterRoute,
  SelectPlanRoute: SelectPlanRoute,
  SettingsRoute: SettingsRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  AdminCafesRoute: AdminCafesRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AdminPlansRoute: AdminPlansRoute,
  MenuSlugRoute: MenuSlugRouteWithChildren,
  ResetPasswordTokenRoute: ResetPasswordTokenRoute,
  VerifyTokenRoute: VerifyTokenRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
